name: country_currency_helper
description: A currency and country select and filter helper.
version: 0.0.2-nullsafety.1
homepage: https://github.com/qreate/country_currency_helper

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"